# Create IAM Role for EKS
Resources:
  MyECSRole:
    Type: "AWS::IAM::Role"
    Properties:
    # Trust policy associated with this role. Only one assume role can be used with a role.
    # Required: Yes
    # Format: JSON or YAML - CF will always convert to JSON before submitting to IAM.
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: "Allow"
          Principal:
            Service:
            - "ec2.amazonaws.com"
          Action:
          - "sts:AssumeRole"
      # The path associated with this role.
      # Required: No
      # Type: String
      Path: "/"
      # The policies to associate to this role.
      # Required: No
      # Type: List of IAM Policies
      Policies:
      - PolicyName: "MyECSPolicy"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action:
            - "eks:*"
            Resource: "*"
